// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4DPm3D94ehWF8t3oWTPE9yiJX9wfwhME',
    appId: '1:594450001835:web:9af0140e017097332decee',
    messagingSenderId: '594450001835',
    projectId: 'dalbong-cafein',
    authDomain: 'dalbong-cafein.firebaseapp.com',
    storageBucket: 'dalbong-cafein.appspot.com',
    measurementId: 'G-QXEMFFH3TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB47_wPcIANi6Xd1diJ6TWbMePUg6atUoU',
    appId: '1:594450001835:android:4e71aa594fe566fd2decee',
    messagingSenderId: '594450001835',
    projectId: 'dalbong-cafein',
    storageBucket: 'dalbong-cafein.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBabk5vCU-_FHx4p4KD0BLK1yMOiV6uu8c',
    appId: '1:594450001835:ios:0a60dae6cb30b90e2decee',
    messagingSenderId: '594450001835',
    projectId: 'dalbong-cafein',
    storageBucket: 'dalbong-cafein.appspot.com',
    iosClientId: '594450001835-4k34qgqcji4atvvi5kk9khqska64323i.apps.googleusercontent.com',
    iosBundleId: 'com.dalbong.cafein',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBabk5vCU-_FHx4p4KD0BLK1yMOiV6uu8c',
    appId: '1:594450001835:ios:d930bd7a1721b92c2decee',
    messagingSenderId: '594450001835',
    projectId: 'dalbong-cafein',
    storageBucket: 'dalbong-cafein.appspot.com',
    iosClientId: '594450001835-std2qrsghv6v7cokp0h5f2ogd2asq7ih.apps.googleusercontent.com',
    iosBundleId: 'com.cafein.cafeinFlutter',
  );
}
