# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
    lane :firebase_deploy do
        build_app(
          scheme: "Runner",
          archive_path: "../build/ios/archive/Runner.xcarchive",
          export_method: "ad-hoc",
          output_directory: "./build/Runner"
        )

        firebase_app_distribution(
            app: "1:594450001835:ios:0a60dae6cb30b90e2decee",
            groups: "ios-테스터",
            ipa_path: "./build/Runner/Runner.ipa"
        )
  end

  desc "iOS App Store Deploy"
    lane :app_store_deploy do |options|
      build_app(
        scheme: "Runner",
        export_method: "app-store",
      )

      api_key = app_store_connect_api_key(
        key_id: "JVSAU2BT96",
        issuer_id: "9c5fabfa-cd77-4406-ae4a-7a83bf75b8f5",
        key_filepath: "./fastlane/AuthKey_JVSAU2BT96.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
      )

      upload_to_app_store(
          api_key: api_key,
          automatic_release: false,
          submit_for_review: false,
          skip_metadata: true,
          skip_screenshots: true,
          skip_app_version_update: true,
          precheck_include_in_app_purchases: false,
      )

    end
end
