# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
    lane :firebase_deploy do
        build_app(
          scheme: "Runner",
          archive_path: "../build/ios/archive/Runner.xcarchive",
          export_method: "ad-hoc",
          output_directory: "./build/Runner"
        )

        firebase_app_distribution(
            app: "1:594450001835:ios:0a60dae6cb30b90e2decee",
            groups: "ios-테스터",
            ipa_path: "./build/Runner/Runner.ipa"
        )
  end
end
