# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Firebase App Distribution"
    lane :firebase_deploy do
        firebase_app_distribution(
            app: "1:594450001835:android:4e71aa594fe566fd2decee",
            groups: "android-테스터",
            apk_path: "../build/app/outputs/apk/release/app-release.apk"
        )
    end

  desc "Android PlayStore Upload"
    lane :play_store_deploy do |options|
        upload_to_play_store(
             track: "internal",
             aab: "../build/app/outputs/bundle/release/app-release.aab",
             release_status: "draft"
        )
    end
end
